export const FETCH_USER_DETAILS = "FETCH_USER_DETAILS";
export const RECEIVE_USER_DETAILS = "RECEIVE_USER_DETAILS";
export const RECEIVE_ERRORS = "RECEIVE_ERRORS";
export const FETCH_ZONES = "FETCH_ZONES";
export const RECEIVE_ZONES = "RECEIVE_ZONES";
export const FETCH_ZONE_SETTINGS = "FETCH_ZONE_SETTINGS";
export const RECEIVE_ZONE_SETTINGS = "RECEIVE_ZONE_SETTINGS";
export const SET_ZONE_SSL = "SET_ZONE_SSL";