export const FETCH_USER_DETAILS = "FETCH_USER_DETAILS";
export const RECEIVE_USER_DETAILS = "RECEIVE_USER_DETAILS";
export const RECEIVE_ERRORS = "RECEIVE_ERRORS";
export const FETCH_ZONES = "FETCH_ZONES";
export const RECEIVE_ZONES = "RECEIVE_ZONES";
